version: '3.4'

services:

    api-project:
        ports:
            - 5858:5858
            - 9229:9229
        command: npm test

    mongo-project:
        container_name: "mongo-project"
        image: mongo:4.0.23-xenial
        hostname: mongo-project
        volumes:
            - ./mongo/db-test:/data/db
        logging:
            driver: "none"
